### ISSUE TITLE
no noise ?

### ISSUE THREAD

**Issue by davephillips** [joelrobichaud/nohmad#1]
Linux Fedora 23
Rack 0.5.0

Your module builds cleanly and instantiates without incident in Rack, but it doesn't seem to be producing any noise. Nothing shows up when I connect its outputs to the Fundamental Scope, am I missing something about how it should be used ?

**Comment by charlie-rbchd** [comment]
I must say I didn't expect anyone to stumble upon this project before I somewhat market it a bit!

This module is a work in progress and only outputs white noise as of yesterday. I will be working on the other outputs this week.

**Comment by davephillips** [comment]
Got it, not a problem. Looking forward to its completion. :)
