### ISSUE TITLE
grey noise?

### ISSUE THREAD

**Issue by metaphorz** [joelrobichaud/nohmad#3]
Looking in the code, it seems like grey noise is not yet implemented. This results in plugs not yielding an output signal for grey. Is it planned? Thanks for the module! It is also an excellent module to study for those doing module development.

**Comment by charlie-rbchd** [comment]
Hi, I'm indeed planning on implementing the grey noise. It should come in pretty soon, stay tuned :)

**Comment by charlie-rbchd** [comment]
Added in commit cc09c4046f631e77ed00f3485083de750732d403.
