### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by ghost** [joelrobichaud/nohmad#4]
Hi!

First of all thanks for your module!
I also want to ask if I could use a part of your code for my S&H module. I would love to include the pink noise.
Of course i will mention that this part of the code (Pink Noise) is coming from you. 

Meanwhile happy coding!

**Comment by charlie-rbchd** [comment]
Sure thing! The pink noise filter was adapted from http://www.firstpr.com.au/dsp/pink-noise/
